dist: zesty
language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dbus dbus-1-dbg libdbus-1-dev
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build -v
  - cargo test
