dist: trusty
language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - libdbus-1-dev
      - libgoogle-perftools-dev
      - libnotmuch-dev
cache: cargo
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUSTFLAGS="-D warnings"
script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
