dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dbus=1.6.18 dbus-1-dbg=1.6.18 libdbus-1-dev=1.6.18
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build -v
  - cargo test
